#!/bin/bash

shopt -s nullglob

cat_file() {
  echo "===================================================================="
  echo "[$1]"
  echo "---"
  cat $1
  echo "===================================================================="
}

PORT=8080
COUNT=30
LOG=httpd.log
ruby -run -e httpd . -p $PORT > $LOG 2>&1 &
#ruby -run -e httpd > $LOG 2>&1 &
pid=$!
trap "kill -9 $pid > /dev/null 2>&1" EXIT
sleep 1
log_size=`wc -c < $LOG`
i=1
while [ $i -le $COUNT ]; do
  echo $i: log_size=$log_size
  curl -s http://localhost:$PORT > response.log
  sleep 5
  new_log_size=`wc -c < $LOG`
  if [ $((new_log_size-log_size)) -gt 100 ]; then
    echo "### Crashed"
    cat_file $LOG
    for f in {~,}/Library/Logs/DiagnosticReports/*ruby*; do
      cat_file $f
    done
    exit
  fi
  log_size=$new_log_size
  ((i++))
done
echo "### No crashed"
cat_file $LOG
